# Generated by Django 3.1.1 on 2020-09-22 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_atuacao', models.CharField(max_length=50, verbose_name='Area de Atuação')),
                ('obj_acao', models.CharField(max_length=50, verbose_name='Objetivo da Ação')),
                ('cnj', models.CharField(max_length=20, verbose_name='Nro do Processo(CNJ)')),
                ('local_tramite', models.CharField(max_length=15, verbose_name='Tramite')),
                ('tramite_uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('nro_processo', models.CharField(max_length=20, verbose_name='Processo')),
                ('dt_contratacao', models.DateField(verbose_name='Data da Contratação')),
                ('dt_encerramento', models.DateField(verbose_name='Data de Encerramento')),
                ('dt_trans_julgado', models.DateField(verbose_name='Data Trânsito de Julgado')),
                ('dt_execucao', models.DateField(verbose_name='Data de Execução')),
                ('dt_sentenca', models.DateField(verbose_name='Data da Sentença')),
                ('vlr_causa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor da Causa')),
                ('pedido', models.CharField(max_length=50, verbose_name='Pedido')),
                ('obs', models.TextField(verbose_name='Obs')),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Advogado Responsavel')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='faseProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fase_processo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('desc', models.TextField(verbose_name='Descrição')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.processo', verbose_name='Processo')),
            ],
        ),
    ]
