# Generated by Django 3.1.3 on 2020-11-28 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20201125_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faseprocesso',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faseprocesso',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.processo'),
        ),
        migrations.AlterField(
            model_name='faseprocesso',
            name='tipo_fase_processo',
            field=models.CharField(max_length=50),
        ),
    ]
