# Generated by Django 3.1.1 on 2021-02-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_auto_20210210_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='nro_processo',
        ),
    ]
