# Generated by Django 5.1.4 on 2025-12-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_remove_processo_nro_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Processo Finalizado'),
        ),
    ]
