# Generated by Django 3.1.1 on 2020-09-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro_endereco', models.CharField(max_length=40, verbose_name='Endereço do Cliente')),
                ('nro_endereco', models.IntegerField(blank=True, null=True, verbose_name='Número do Cliente')),
                ('nome_bairro', models.CharField(max_length=45, verbose_name='Bairro')),
                ('cidade_endereco', models.CharField(max_length=15, verbose_name='Cidade')),
                ('nome_uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='Nome')),
                ('ctps_cliente', models.CharField(max_length=10, verbose_name='Carteira de Trabalho')),
                ('profissao_cliente', models.CharField(max_length=50, verbose_name='Profissão')),
                ('cpf', models.CharField(max_length=14, verbose_name='Número do CPF')),
                ('rg', models.CharField(max_length=8, verbose_name='Número de RG')),
                ('nacionalidade', models.CharField(max_length=50, verbose_name='Nacionalidade')),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('U', 'União Estavel'), ('V', 'Viuvo(a)')], max_length=1, verbose_name='Estado Civil')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('escolaridade', models.CharField(choices=[('FI', 'Ensino Fundamental Incompleto'), ('FC', 'Ensino Fundamental Completo'), ('MI', 'Ensino Médio Incompleto'), ('MC', 'Ensino Médio Completo'), ('SI', 'Ensino Superior Incompleto'), ('SC', 'Ensino Superior Completo')], max_length=2, verbose_name='Escolaridade')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('observacao', models.TextField(verbose_name='Obs')),
                ('cidade_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.endereco', verbose_name='Endereço')),
            ],
        ),
    ]
