# Generated by Django 3.1.1 on 2020-09-22 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=django.utils.timezone.now, max_length=11, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
