# Generated by Django 3.1.1 on 2020-10-25 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cidade_endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ctps_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='escolaridade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='profissao_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default=django.utils.timezone.now, max_length=45, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default=django.utils.timezone.now, max_length=8, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=django.utils.timezone.now, max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nro_endereco',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número do Cliente'),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
